# Generated by Django 3.0.8 on 2020-08-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': "Todo's"},
        ),
        migrations.AddField(
            model_name='todo',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
